### ISSUE TITLE
Do you have a trained model (checkpoint) for this?

### ISSUE THREAD

**Issue by LiuTingWed** [NoamRosenberg/AutoML#62]
hi ! this is an amazing work ! 
I just wanna use this project to do some researches but my PC too slow.
Can you support a trained model for this ? 
thanks.

**Comment by zhizhangxian** [comment]
Do you mean search or retrain?

**Comment by LiuTingWed** [comment]
yes, I am so appriciate if you can support

**Comment by zhizhangxian** [comment]
But No the result is not very good. if you want, maybe I can offer a baiduyun drive

**Comment by LiuTingWed** [comment]
Never mind, thanks :-)

**Comment by LiuTingWed** [comment]
I am so interesting about this paper and your work implement to Pytorch.
But as the figure that you provide implementation result see, it's curve is almost match the paper result.
Why you said the search result is not very good ?

**Comment by zzx-zhangxian** [comment]
miou is lower than paper reports

**Comment by LiuTingWed** [comment]
Oh,too strange,
do you figure out this issue should be?
do you finally search the cell architecture as same as the paper?

**Comment by zzx-zhangxian** [comment]
No, now we dont solve this issue.
The architect after search is different from paper reports obviously, If run darts, I  dont get the same result as paper too...

**Comment by LiuTingWed** [comment]
what a pity!
If you don't mind, please tell me the reason when you figure out.
By the way,what GPU you use to train, P100?

**Comment by zzx-zhangxian** [comment]
in search V100 *1
in retrain 2080ti * 8

**Comment by zzx-zhangxian** [comment]
Hey, boy, we have know get a better result for search, it has 0.34miou

baiduyun drive：https://pan.baidu.com/s/1ASRyzK_0m9CvhfN3yHZZ5Q 
passwd：px6y

**Comment by LiuTingWed** [comment]
thanks :-)

**Comment by Sunshine-Ye** [comment]
> in search V100 *1
> in retrain 2080ti * 8

hi ! thanks for doing such amazing work !
If it is convenient, can you tell me how long do you need to finish retrain with 2080ti * 8? 
and how high performance can be achieved with the derived model in the paper  ?
@zhizhangxian

**Comment by zzx-zhangxian** [comment]
I trained for about 1M iters on autodeeplab-M I remembered, not used SDP, and got 79.8miou without MS

**Comment by zzx-zhangxian** [comment]
total train time is about 20 days

**Comment by Sunshine-Ye** [comment]
thanks for your quick reply！
1.SDP means the Scheduled Drop Path method？MS means using multi_scale in train？79.8 miou is evaluated under multi-scale or not？
2.what kind of training do you use：python train.py or CUDA_VISIBLE_DEVICES=0,1,2,···,n python -m torch.distributed.launch --nproc_per_node=n train_distributed.py ？
3.20 days for retrain is a bit too long, it Is caused by the training code or the model itself? can you share the direction of optimization?
4.I have tried to retrain，but the retrain default args and train_distributed.py are not properly set. Although I've tuned the code, I don't know if the parameters are set correctly. can you give me some advice?
look like to your reply, sincerely.

**Comment by zzx-zhangxian** [comment]
1. yes, not under ms I remember, I adapt the retrain code from chenxi's deeplab v3 reproduce, he didnot use MS
2. if you mean retrain, you should use CUDA_VISIBLE_DEVICES=0,1,2,···,n python -m torch.distributed.launch --nproc_per_node=n train_distributed.py to use distributed training
3. It is just because too much iterations(more than 1M in paper) and only 30K in deeplab v3plus, you can not get a good result if train only several thousands iters without imageNet pretrain, the retrain configurations are same as deeplab v3/v3+
4. I retrained it with another code(adapted from chenxi's code), I should have fixed the bugs in our project, but these days I am busy in some other things, but maybe I can pay some attention on it after March...
Thanks, good luck!

**Comment by Sunshine-Ye** [comment]
thank you very much！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhizhangxian"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月11日(星期六) 晚上11:48
收件人:&nbsp;"NoamRosenberg/AutoML"<AutoML@noreply.github.com&gt;;
抄送:&nbsp;"0.0"<1639998780@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [NoamRosenberg/AutoML] Do you have a trained model (checkpoint) for this? (#62)



 
yes, not under ms I remember, I adapt the retrain code from chenxi's deeplab v3 reproduce, he didnot use MS
 
if you mean retrain, you should use CUDA_VISIBLE_DEVICES=0,1,2,···,n python -m torch.distributed.launch --nproc_per_node=n train_distributed.py to use distributed training
 
It is just because too much iterations(more than 1M in paper) and only 30K in deeplab v3plus, you can not get a good result if train only several thousands iters without imageNet pretrain, the retrain configurations are same as deeplab v3/v3+
 
I retrained it with another code(adapted from chenxi's code), I should have fixed the bugs in our project, but these days I am busy in some other things, but maybe I can pay some attention on it after March...
 Thanks, good luck!
